ignore:
    - "**/*.test"
fixes:
    - "\\+opentelemetry/\\+sdk/\\+trace/::sdk/trace/+opentelemetry/+sdk/+trace/"
    - "\\+opentelemetry/\\+sdk/\\+metrics/::sdk/metrics/+opentelemetry/+sdk/+metrics/"    
    - "\\+opentelemetry/\\+sdk/\\+common/::sdk/common/+opentelemetry/+sdk/+common/"
    - "\\+opentelemetry/\\+trace/::api/trace/+opentelemetry/+trace/"
    - "\\+opentelemetry/\\+metrics/::api/metrics/+opentelemetry/+metrics/"
    - "\\+opentelemetry/\\+context/::api/context/+opentelemetry/+context/"
    - "\\+opentelemetry/\\+common/::api/common/+opentelemetry/+common/"
    - "\\+opentelemetry/\\+baggage/::api/baggage/+opentelemetry/+baggage/"
    - "\\+opentelemetry/\\+exporters/\\+otlp/::exporters/otlp/+opentelemetry/+exporters/+otlp/"
    - "\\+opentelemetry/\\+sdk/\\+logs::sdk/logs/+opentelemetry/+sdk/+logs/"
    - "\\+opentelemetry/\\+logs/::api/logs/+opentelemetry/+logs/"